definitions:
  helpers.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
      validation:
        additionalProperties:
          type: string
        type: object
    type: object
  mongo_model.SeasonStatus:
    enum:
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - SeasonStatusActive
    - SeasonStatusInactive
  request.AdminLoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.MemberLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.MemberRegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  request.ResendEmailVerificationRequest:
    properties:
      email:
        type: string
    type: object
  request.SeasonStatusUpdateRequest:
    properties:
      status:
        $ref: '#/definitions/mongo_model.SeasonStatus'
    type: object
  request.SuperadminLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.VenueCreateRequest:
    properties:
      name:
        type: string
    type: object
  request.VenueUpdateRequest:
    properties:
      name:
        type: string
    type: object
  request.VerifyEmailRequest:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/auth/login:
    post:
      consumes:
      - application/json
      description: Login Admin
      parameters:
      - description: Login Admin
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.AdminLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      summary: Login Admin
      tags:
      - Auth-Admin
  /admin/auth/profile:
    get:
      consumes:
      - application/json
      description: Get Profile Admin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Get Profile Admin
      tags:
      - Auth-Admin
  /member/auth/login:
    post:
      consumes:
      - application/json
      description: Login Member
      parameters:
      - description: Login Member
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.MemberLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      summary: Login Member
      tags:
      - Auth-Member
  /member/auth/profile:
    get:
      consumes:
      - application/json
      description: Get Profile Member
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Get Profile Member
      tags:
      - Auth-Member
  /member/auth/register:
    post:
      consumes:
      - application/json
      description: Register Member
      parameters:
      - description: Register Member
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.MemberRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helpers.Response'
      summary: Register Member
      tags:
      - Auth-Member
  /member/auth/resend-email-verification:
    post:
      consumes:
      - application/json
      description: Resend Verify Email Member
      parameters:
      - description: Resend Verify Email Member
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.ResendEmailVerificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      summary: Resend Verify Email Member
      tags:
      - Auth-Member
  /member/auth/verify-email:
    post:
      consumes:
      - application/json
      description: Verify Email Member
      parameters:
      - description: Verify Email Member
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.VerifyEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      summary: Verify Email Member
      tags:
      - Auth-Member
  /superadmin/auth/login:
    post:
      consumes:
      - application/json
      description: Login Superadmin
      parameters:
      - description: Login Superadmin
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.SuperadminLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Login Superadmin
      tags:
      - Auth-Superadmin
  /superadmin/auth/profile:
    get:
      consumes:
      - application/json
      description: Get Profile Superadmin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Get Profile Superadmin
      tags:
      - Auth-Superadmin
  /superadmin/seasons:
    get:
      consumes:
      - application/json
      description: Get Seasons
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      - description: Direction asc or desc
        in: query
        name: dir
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Get Seasons
      tags:
      - Season-Superadmin
    post:
      consumes:
      - multipart/form-data
      description: Create Season
      parameters:
      - in: formData
        name: name
        required: true
        type: string
      - description: Logo
        in: formData
        name: logo
        required: true
        type: file
      - description: Banner
        in: formData
        name: banner
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Create Season
      tags:
      - Season-Superadmin
  /superadmin/seasons/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Season
      parameters:
      - description: Season ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Delete Season
      tags:
      - Season-Superadmin
    get:
      consumes:
      - application/json
      description: Get Season Detail
      parameters:
      - description: Season ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Get Season Detail
      tags:
      - Season-Superadmin
    put:
      consumes:
      - multipart/form-data
      description: Update Season
      parameters:
      - description: Season ID
        in: path
        name: id
        required: true
        type: string
      - in: formData
        name: name
        required: true
        type: string
      - description: Logo
        in: formData
        name: logo
        type: file
      - description: Banner
        in: formData
        name: banner
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Update Season
      tags:
      - Season-Superadmin
  /superadmin/seasons/{id}/status:
    put:
      consumes:
      - application/json
      description: Update Season Status
      parameters:
      - description: Season ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Season Status
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.SeasonStatusUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Update Season Status
      tags:
      - Season-Superadmin
  /superadmin/venues:
    get:
      consumes:
      - application/json
      description: Get Venues List
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      - description: Direction asc or desc
        in: query
        name: dir
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Get Venues List
      tags:
      - Venue-Superadmin
    post:
      consumes:
      - application/json
      description: Create Venue
      parameters:
      - description: Create Venue
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.VenueCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Create Venue
      tags:
      - Venue-Superadmin
  /superadmin/venues/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Venue
      parameters:
      - description: Venue ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Delete Venue
      tags:
      - Venue-Superadmin
    get:
      consumes:
      - application/json
      description: Get Venue Detail
      parameters:
      - description: Venue ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Get Venue Detail
      tags:
      - Venue-Superadmin
    put:
      consumes:
      - application/json
      description: Update Venue
      parameters:
      - description: Venue ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Venue
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.VenueUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - BearerAuth: []
      summary: Update Venue
      tags:
      - Venue-Superadmin
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
